NUCLEO_OPERACIONAL_ATIVO = False

AGENTE_CENTRAL_ATIVO = True

AGENTE_COORDENACAO_ATIVO = True

AGENTE_COMUNICACAO_ATIVO = True

AGENTE_PESQUISA_AVANCADA_ATIVO = True

AGENTE_MEMORIA_ESTRATEGICA_ATIVO = True

AGENTE_GESTAO_CONHECIMENTO_ATIVO = True
